import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Page config
st.set_page_config(
    page_title="Brain Tumor Detection",
    page_icon="🧠",
    layout="centered"
)

# Load model
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("brain_tumor_model.h5")

model = load_model()

# Class labels
class_names = ["Glioma", "Meningioma", "Pituitary", "No Tumor"]

# Title
st.title("🧠 Brain Tumor Detection System")
st.write("Upload an MRI image to detect brain tumor type.")

# Upload image
uploaded_file = st.file_uploader(
    "Upload Brain MRI Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded MRI Image", use_column_width=True)

    # Preprocess
    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    prediction = model.predict(img_array)
    predicted_class = class_names[np.argmax(prediction)]
    confidence = np.max(prediction) * 100

    st.markdown("### 🔍 Prediction Result")
    st.success(f"Tumor Type: **{predicted_class}**")
    st.info(f"Confidence: **{confidence:.2f}%**")

    # Explanation
    st.markdown("### 🧠 AI Explanation")
    st.write(
        f"""
        The deep learning model detected patterns commonly associated with **{predicted_class}**.
        A confidence score of **{confidence:.2f}%** indicates moderate certainty in this prediction.

        ⚠️ **Disclaimer:**  
        This result is generated by an AI system and is **not a medical diagnosis**.
        Please consult a qualified medical professional for accurate evaluation.
        """
    )
